{
  stdenv,
  swift,
  swiftpm,
  swiftpm2nix,
}:
let
  # Nix dir generated by running `swiftpm2nix` in the upstream project
  deps = swiftpm2nix.helpers ./nix;
in
stdenv.mkDerivation rec {
  name = "autokbisw";
  version = "2.0.1";
  src = builtins.fetchTarball {
    url = "https://github.com/ohueter/autokbisw/archive/refs/tags/${version}.tar.gz";
    sha256 = "sha256:1xz2l08s7zw5g83c5yqx27sxy134d5l4xljdi9fwlnyn6a0dgmf4";
  };
  nativeBuildInputs = [
    swift
    swiftpm
  ];
  configurePhase = deps.configure;
  buildPhase = "swift build --configuration release";
  installPhase = "mkdir -p $out/bin; install -t $out/bin ./.build/release/autokbisw";
}
